### ISSUE TITLE
[COMPATABILITY WITH FARMER'S DELIGHT]

### ISSUE THREAD

**Issue by Chorderline** [xR4YM0ND/NutritionZ#1]
It does not seem to be compatible with Farmer's Delight, or any other food mod I've tried. This mod is already awesome and insanely vanilla friendly. Compatability is its only downside.

**Comment by xR4YM0ND** [comment]
You can add compat with datapacks

**Comment by Globox1997** [comment]
Added farmers delight compat with [https://github.com/xR4YM0ND/NutritionZ/commit/deba8846055844101f750f4b7816aa2604235bbc](https://github.com/xR4YM0ND/NutritionZ/commit/deba8846055844101f750f4b7816aa2604235bbc) by illustietor.
