### ISSUE TITLE
[IDEA] Support for new mods of [Let's Do].

### ISSUE THREAD

**Issue by YOUNIN15** [xR4YM0ND/NutritionZ#12]
Support for new mods of [Let's Do].

There are several mods from this series that have been revamped for greater compatibility with others in the same series. So these new versions are better, add more stuff and better compatibility with [Let's Do] Farm & Charm.

[Let's Do] Candlelight - Farm&Charm compat

[Let's Do] Brewery - Farm&Charm Compat

[Let's Do] Bakery - Farm&Charm Compat

**Comment by xR4YM0ND** [comment]
Added default support with 2b43337f784fb376e6e05a537790db63326e5f27
