### ISSUE TITLE
[IDEA] Negative nutrition values

### ISSUE THREAD

**Issue by luxlacis** [xR4YM0ND/NutritionZ#14]
Make it possible to have negative nutrition values. Makes it possible to add "bad" foods using datapacks that take away your nutrition.

**Comment by xR4YM0ND** [comment]
This feature is kinda against the balance system as of right now.

If you consume 1 hunger , each nutrient value decreases by 1 

So if a nutrient is 0 -> its -1 times hunger ( or saturation ) for that nutrient
