### ISSUE TITLE
[IDEA] Pam's HarvestCraft 2 Compat?

### ISSUE THREAD

**Issue by Cynide0592** [xR4YM0ND/NutritionZ#17]
Would it be possible to create a Compat for Pam's HarvestCraft 2, as not mentioned in list of current compatible mods.

**Comment by xR4YM0ND** [comment]
Pam's HarvestCraft is for Forge & Neoforge, not for Fabric.

If there is a fabric port pls send me a link or project name here & i will do a compat.

**Comment by Cynide0592** [comment]
Thank you for replying, I'll see if the developer has a fabric version or is wiling to port one and let you know, thanks again

**Comment by leohearts** [comment]
> Pam's HarvestCraft is for Forge & Neoforge, not for Fabric.
> 
> If there is a fabric port pls send me a link or project name here & i will do a compat.

We can use [Sinytra Connector](https://github.com/Sinytra/Connector) to load fabric mods in neoforge. And currently NutritionZ works very well :3 I'm also looking for HarvestCraft2(plus croptopia) compat and guided me here.

**Comment by xR4YM0ND** [comment]
I will only add default compat for fabric mods.

Although you can add compat via datapack for other mods.

**Comment by leohearts** [comment]
> I will only add default compat for fabric mods.
> 
> Although you can add compat via datapack for other mods.

Sure! Should we make a pull request here and make it bundled as default, or we post it somewhere else ?
