### ISSUE TITLE
[NEW NUTRITION BUFFS]

### ISSUE THREAD

**Issue by Chorderline** [xR4YM0ND/NutritionZ#2]
Carbs granting fire resistance seems unfitting, IMO. These are my suggestions for the nutritional buffs:
Carbs: Speed
Proteins: Strength
Fats: Regeneration
Vitamins: More Hearts
Minerals: Absorption

**Comment by xR4YM0ND** [comment]
Will apply most of your suggestions in the next update

**Comment by xR4YM0ND** [comment]
Added most of them in 1.0.1
