### ISSUE TITLE
[Question]  what's the difference?

### ISSUE THREAD

**Issue by lostopkk** [xR4YM0ND/NutritionZ#3]
What is the difference between using this mod and using the diet mod?
https://modrinth.com/mod/diet

**Comment by Globox1997** [comment]
The main difference is the value mechanic of food.
NutritionZ is not compatible with food mods by default, it requires a datapack.
Diet in comparison is compatible with most if not all food mods and works in percentage.

**Comment by lostopkk** [comment]
> The main difference is the value mechanic of food. NutritionZ is not compatible with food mods by default, it requires a datapack. Diet in comparison is compatible with most if not all food mods and works in percentage.

thanks
