### ISSUE TITLE
[IDEA] Do not pause the game when viewing the nutrition screen

### ISSUE THREAD

**Issue by kyber-6** [xR4YM0ND/NutritionZ#6]
**Describe your idea in depth.**

I am unsure if this is intentional or not, but currently the game pauses when you view the nutrition screen. I believe it makes sense not to pause the game when viewing the nutrition screen in your inventory, since for example when viewing the LevelZ or JobsAddon screen the game does not pause.

**Comment by xR4YM0ND** [comment]
Changed this via https://github.com/xR4YM0ND/NutritionZ/commit/9738b099359be9ccdfc08797f3900351ccf501ec
